# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  schedule: 
  - cron: "0 * * * *"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Sync and merge upstream repository with your current repository
      uses: dabreadman/sync-upstream-repo@v1.0.0.b
      with:
        # URL of gitHub public upstream repo
        upstream_repo: "https://github.com/rittaschool/ritta-next.git"
        # Branch to merge from upstream (defaults to downstream branch)
        upstream_branch: master
        # Branch to merge into downstream
        downstream_branch: master
        # GitHub Bot token
        token: ${{ secrets.GITHUB_TOKEN }}
